#!/usr/bin/env ruby

#
# == Usage
# orcResourceChecker
# 

require 'rubygems'
require 'active_record'
require 'getoptlong'


require 'orc/ORC_Environment'


# MAIN script function
def main

   include ORC

   @bUp           = false
   @bDown         = false
   @bUpdate       = false
   @bExport       = false
   @bShowVersion  = false
   @bShowUsage    = false
   
   opts = GetoptLong.new(
     ["--export-rows",     "-e",       GetoptLong::NO_ARGUMENT],
     ["--version", "-v",               GetoptLong::NO_ARGUMENT],
     ["--usage",   "-u",               GetoptLong::NO_ARGUMENT],
     ["--help",            "-h",       GetoptLong::NO_ARGUMENT]
     )
    
   begin
      opts.each do |opt, arg|
         case opt      
            when "--usage"             then @bShowUsage           = true
			   when "--help"              then @bShowUsage           = true
            when "--version"           then @bShowVersion         = true
         end
      end
   rescue Exception => e
      # puts e.to_s
      exit(99)
   end

   if @bShowVersion == true then
      print("\nESA - DEIMOS-Space S.L. ", File.basename($0), " Version: [#{ORC::VERSION}]", "\n")
      hRecord = ORC::CHANGE_RECORD
      hRecord.each_pair{|key, value|
         puts "#{key} => #{value}"
      }
      exit(0)
   end

   # -------------------------------------------------------

   if @bShowUsage == true then
      usage
      exit(0)
   end

   # -------------------------------------------------------

   # -------------------------------------------------------


   iValue = Kernel.rand(0..19)
   puts iValue
 
   if iValue == 0 then
      exit(-1)
   else
      exit(0)
   end

end

#-------------------------------------------------------------

def usage
   fullpathFile = File.expand_path(__FILE__)
      
   value = `#{"head -6 #{fullpathFile}"}`
      
   value.lines.drop(1).each{
      |line|
      len = line.length - 1
      puts line[2, len]
   }
end

#-------------------------------------------------------------


#=====================================================================
# Start of the main body
main
# End of the main body
#=====================================================================
