#!/usr/bin/env ruby

#########################################################################
##
## === Ruby source for #ORC_TestCases class
##
## === Written by DEIMOS Space S.L. (bolf)
##
## === Orchestrator Component
## 
## module ORC
##
#########################################################################

require 'rubygems'
require 'test/unit'
require 'fileutils'

require 'cuc/DirUtils'
require 'cuc/Log4rLoggerFactory'

require 'orc/ORC_Environment'
require 'arc/MINARC_Environment'




## Preconditions:
#
## 0.1 - rake -f build_minarc.rake minarc:install[naosboa,orc_boa,naos_test_pg]
## 0.2 - rake -f build_orc.rake orc:install[boatest,orc_boa]
#
# 1 - setup 
# 1.1 - load_config_development
# 1.2 - inventory database is created

# 2 - teardown
# 2.1 - purge archive
# 2.2 - inventory database is destroyed


# Select a single test of the suite

# ruby orcUnitTests -n test_my_method 


class ORCTestCaseBOA < Test::Unit::TestCase

   include CUC::DirUtils
   include ORC

   
   # Order of the test cases execution according to defintion within code
   self.test_order = :defined
   
   @my_argv = ARGV.dup
   
   # --------------------------------------------------------
   
   Test::Unit.at_start do
      
      system("clear")
        
      puts
      puts "======================================"
      puts "ORC Unit Test Cases"
      puts
      puts
      puts "DO NOT EXECUTE IN THE PRODUCTION ENVIRONMENT !!!!!"
      puts
      puts "or with operational data in the archive"
      puts
      puts "THINK CAREFULLY !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      bBatchmode     = false
      @@execEnvFile  = ""
      
            
      @my_argv.each{|arg|
      
         if arg.include?(".env") == true then
            @@execEnvFile = arg.to_s
         end
      
         if arg == "batchmode" then
            puts "batch mode execution on"
            bBatchmode = true
         end
      }
      
      if bBatchmode == false then
         c = STDIN.getc   
         if c != 'Y' then
            exit(99)
         end
      end
      
      
=begin
      puts
      puts
      puts "THINK IT TWICE  !!! "
      puts
      puts "do you want to continue Y/n" 
      puts
      puts
      
      c = STDIN.getc
            
      
      if c != 'Y' then
         exit(99)
      end

=end      
      
#      ret = `which`
#      
#      puts $?.exitstatus
#      
#      if $?.exitstatus != 1 then
#         puts "which command line tool is missing"
#         puts
#         exit(99)
#      end
#      
      @@conf = ORC_Environment.new
      
      if @@execEnvFile != nil and @@execEnvFile != "" then
         ret = @@conf.wrapper_load_environment(@@execEnvFile)
         if ret == false then
            puts "Aborting test !"
            exit(99)
         end
      else     
         @@conf.wrapper_load_config
      end

      puts "--------------------------"     
      @@conf.wrapper_print_environment
      puts "--------------------------"
     
     
#      # ENV['ORC_DATABASE_HOST'] = "localhost_non_existing"
#      ENV['ORC_DATABASE_HOST'] = "localhost"     
     
      puts
      puts "--------------------------"       
      @@conf.wrapper_print_environment
      puts "--------------------------"
      puts
     
            
      @@conf.wrapper_createEnvironmentDirs

      if @@conf.wrapper_check_environment == false then
         puts "orchestrator environment not suited for ORC unit tests"
         puts
         exit(99)
      end
   
      orcConfig = ENV['ORC_CONFIG']
      
      @@conf.unset_config

      ENV['ORC_CONFIG'] = orcConfig
   
      puts "--------------------------"     
      @@conf.wrapper_print_environment
      puts "--------------------------"

      
      require 'orc/ReadOrchestratorConfig'
      
      @@pollingDir = ORC::ReadOrchestratorConfig.instance.getPollingDir
      
      @@conf = MINARC_Environment.new

      ## minArc configuration is now shipped within the gem
      ## and it is used the one installed
#      @@conf.wrapper_load_config_development
#
#      if @@execEnvFile == nil or @@execEnvFile == "" then
#         @@conf.wrapper_load_environment_test
#      end

      puts
      puts "Creating minARC directories"

      @@conf.wrapper_load_config

      @@conf.wrapper_createEnvironmentDirs
      
      if @@conf.wrapper_check_environment == false then
         puts "minArc environment not suited for ORC unit tests"
         puts
         exit(99)
      else
         puts      
         @@conf.wrapper_print_environment
         puts
      end
         
   
      @@arrInputFiles = [ \
         "source.json", \
         "properties.json", \
         "irrelevant_name", \
         "extension.1.2.3", \
         "I_love_your_name" \
         ]
    
           @orcConfigDir = ENV['ORC_CONFIG']
      require 'orc/ReadOrchestratorConfig'
 

      ## ----------------------------------
      ## initialize logger
      loggerFactory = CUC::Log4rLoggerFactory.new("ORCTEST", "#{@orcConfigDir}/orchestrator_log_config.xml")
   
      @@logger = loggerFactory.getLogger   
      if @@logger == nil then
         puts
		   puts "Error in OrchestratorIngester::initialize"
     	   puts "Could not initialize logging system !  :-("
         puts "Check ORC logs configuration under \"#{@orcConfigDir}/orchestrator_log_config.xml\"" 
 	      puts
   	   exit(99)
      end

      ## ----------------------------------
        
            
   end
   
   ## ------------------------------------------------------
   
   Test::Unit.at_exit do
      @@logger.info("START => ORCTestCaseBOA::#{__method__.to_s}")
      @@logger.info("END   => ORCTestCaseBOA::#{__method__.to_s}")
   end
   
   ## ------------------------------------------------------ 
   
   ## Setup before every test-case
   ##
   def setup
      @@logger.info("START => ORCTestCaseBOA::#{__method__.to_s}")
      
      cmd = "rm -f /log/naosboa_orc*.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/minarc/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/minarc_error2/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/orc_tmp/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/processorWd/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/success/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -rf /tmp/tmp/*"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "rm -f /tmp/breakpoints/*"
      @@logger.debug(cmd)
      system(cmd)

      @@logger.info("END   => ORCTestCaseBOA::#{__method__.to_s}")
   end
   ## --------------------------------------------------------
   ## After every test case

   def teardown
      @@logger.info("START => ORCTestCaseBOA::#{__method__.to_s}")
      @@logger.info("END   => ORCTestCaseBOA::#{__method__.to_s}")
   end
   ## ------------------------------------------------------


   ## ------------------------------------------------------

   def testConfig
      @@logger.info("START => ORCTestCaseBOA::#{__method__.to_s}")

      orcConf = ORC::ReadOrchestratorConfig.instance
      orcConf.update
      
      assert( orcConf.isValidFileType?("NS1_TEST_CNF_OAT____20220709T004210_20220716T230832_0001"), "valid file ?" ) 

      @@logger.info("END   => ORCTestCaseBOA::#{__method__.to_s}")
   end
 
   ## -----------------------------------------------------------

   def test_queue_file

      FileUtils.rm_f("/log/naosboa_orc*.log")
      @@logger.info("START => ORCTestCaseBOA::#{__method__.to_s}")

      cmd = "minArcDB -d"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "minArcDB -c"
      @@logger.debug(cmd)
      system(cmd)

      system("echo 'holy crap' > /tmp/minarc/tmp/source.json")
      cmd = "minArcStore -t DUMMY -f \"/tmp/minarc/tmp/source.json\" --noserver"
      @@logger.debug(cmd)
      assert(system(cmd), "store of source.json")
      
      cmd = "minArcStatus -f source.json --noserver | jq"
      @@logger.debug(cmd)
      assert(system(cmd), "status of source.json")

      cmd = "minArcRetrieve -f source.json -L /inputs --noserver"
      @@logger.debug(cmd)
      assert(system(cmd), "retrieve of source.json")

      cmd      = 'orcQueueInput -f source -P -s NRT'
      @@logger.debug(cmd)
      retVal   = system(cmd)
      if @isDebugMode == true then
         @logger.debug("#{cmd} / #{retVal}")
      end

      @@logger.info("END   => ORCTestCaseBOA::#{__method__.to_s}")
   end
   ## -----------------------------------------------------------

   def test_train_slow
      @@logger.info("START => ORCTestCaseBOA::#{__method__.to_s}")

      FileUtils.rm_f("/log/naosboa_orc*.log")
      
      @@logger.info("orcUnitTests::#{__method__.to_s} START")

      require 'orc/ReadOrchestratorConfig'
      
      orcConf = ORC::ReadOrchestratorConfig.instance
      orcConf.update
      pollingDir = orcConf.getPollingDir
     
      cmd = "rm -rf #{pollingDir}/*"
      @@logger.debug(cmd)
      system(cmd)
      
      system("orcBolg -c stop")
      sleep(5.0)

      system("minArcPurge -Y")
      system("minArcDB -d")
      system("minArcDB -c")
      
      system("orcManageDB -d")
      system("orcManageDB -c")

      cmd = "rm -f /log/naosboa_orc*.log"
      @@logger.debug(cmd)
      system(cmd)

      cmd = "orcBolg -c start"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)
   
      @@arrInputFiles.each{|filename|
         @@logger.debug("orcUnitTests::#{__method__.to_s} #{filename}")
         system("echo \'#{filename}\' > #{pollingDir}/#{filename}")
         @@logger.info("orcUnitTests::#{__method__.to_s} file created at #{pollingDir}/#{filename}")
         sleep(10)
      }
      
      sleep(2)
      
      cmd = "orcQueueInput -l -Q"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      cmd = "orcQueueInput -l -P"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      cmd = "orcQueueInput -l -F"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      cmd = "orcQueueInput -l -S"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      arr = Dir["/log/naosboa_orc*.log"]
      cmd = "grep ERROR #{arr[0]}"
      @@logger.debug(cmd)
      assert(!system(cmd), "ERROR found in orchestrator logs  #{arr[0]} in #{__method__.to_s}") 
   
      system("orcBolg -c stop")
      sleep(4.0)
      
      @@logger.info("orcUnitTests::#{__method__.to_s} END")
      arr = Dir["/tmp/naosboa_orc*.log"]
      cmd = "cp #{arr[0]} /tmp/LOG_ORCUnitTest_NAOS_#{__method__.to_s}"
      @@logger.debug(cmd)
      system(cmd)
     
      @@logger.info("END   => ORCTestCaseBOA::#{__method__.to_s}")
   end

   ## -----------------------------------------------------------

   def test_train
     
      puts "================================================"
      puts "ORC_UnitTests::#{__method__.to_s}"
      puts

      require 'orc/ReadOrchestratorConfig'
      
      orcConf = ORC::ReadOrchestratorConfig.instance
      orcConf.update
      pollingDir = orcConf.getPollingDir
     
      FileUtils.rm_f("/log/naosboa_orc*.log")
      
      cmd = "rm -f /log/naosboa_orc*.log"
      puts cmd
      system(cmd)

      cmd = "rm -f /tmp/orc_tmp/*"
      puts cmd
      system(cmd)
  
      cmd = "rm -rf /tmp/tmp/*"
      puts cmd
      system(cmd)
  
      @@logger.info("orcUnitTests::#{__method__.to_s} START")
      
      
      system("orcBolg -c stop")
      sleep(5.0)

      system("minArcPurge -Y")
      system("minArcDB -d")
      system("minArcDB -c")
      
      system("orcManageDB -d")
      system("orcManageDB -c")

      cmd = "orcBolg -c start"
      assert(system(cmd), cmd)
   
      @@arrInputFiles.each{|filename|
         cmd = "echo \'#{filename}\' > #{pollingDir}/#{filename}"
         ret = system(cmd)
         @@logger.debug("#{cmd} / #{ret}")
         sleep(1)
      }
      
      sleep(250)
      
      
      cmd = "orcQueueInput -l -Q"
      puts cmd
      puts
      assert(system(cmd), cmd)

      cmd = "orcQueueInput -l -P"
      puts cmd
      puts
      assert(system(cmd), cmd)


      cmd = "orcQueueInput -l -F"
      puts cmd
      puts
      assert(system(cmd), cmd)


      cmd = "orcQueueInput -l -S"
      puts cmd
      puts
      assert(system(cmd), cmd)

      
      arr = Dir["/log/naosboa_orc*.log"]
      cmd = "grep ERROR #{arr[0]}"
      puts cmd
      assert(!system(cmd), "ERROR found in orchestrator logs in #{__method__.to_s}") 
   
      system("orcBolg -c stop")
      sleep(5.0)

      @@logger.info("orcUnitTests::#{__method__.to_s} END")
      arr = Dir["/log/naosboa_orc*.log"]
      cmd = "cp #{arr[0]} /tmp/LOG_ORCUnitTest_#{__method__.to_s}"
      puts cmd
      system(cmd)
   
   end
   ## -----------------------------------------------------------

   def test_allatonce

      puts "================================================"
      puts "ORC_UnitTests::#{__method__.to_s}"
      puts
     
      @@logger.info("orcUnitTests::#{__method__.to_s} START")     
      
      orcConf = ORC::ReadOrchestratorConfig.instance
      orcConf.update
      pollingDir = orcConf.getPollingDir
                
      system("orcBolg -c stop")
      sleep(5.0)

      system("minArcPurge -Y")
      system("minArcDB -d")
      system("minArcDB -c")
      
      system("orcManageDB -d")
      system("orcManageDB -c")
     
      @@arrInputFiles.each{|filename|
         cmd = "echo \'#{filename}\' > #{pollingDir}/#{filename}"
         ret = system(cmd)
         @@logger.debug("#{cmd} / #{ret}")
      }

      sleep(3.0)

      cmd = "orcBolg -c start"
      assert(system(cmd), cmd)
      @@logger.debug("sleep for 300 secs zzZZZZzzzzzZZZZZZZzzzzz")
      sleep(300)

      cmd = "orcQueueInput -l -Q"
      puts cmd
      puts
      assert(system(cmd), cmd)

      cmd = "orcQueueInput -l -P"
      puts cmd
      puts
      assert(system(cmd), cmd)


      cmd = "orcQueueInput -l -F"
      puts cmd
      puts
      assert(system(cmd), cmd)


      cmd = "orcQueueInput -l -S"
      puts cmd
      puts
      assert(system(cmd), cmd)

      cmd = "orcBolg -c stop"
      @@logger.debug(cmd)
      assert(system(cmd), cmd)

      arr = Dir["/log/naosboa_orc*.log"]
      cmd = "grep ERROR #{arr[0]}"
      puts cmd
      assert(!system(cmd), "ERROR found in orchestrator logs in #{__method__.to_s}") 


      @@logger.info("orcUnitTests::#{__method__.to_s} END")
      arr = Dir["/log/naosboa_orc*.log"]
      cmd = "cp #{arr[0]} /tmp/LOG_ORCUnitTest_#{__method__.to_s}"
      puts cmd
      system(cmd)
      

   end
      
   ## -------------------------------------------------------------

  
   
   ## -------------------------------------------------------------

   
   
   
   
   ## --------------------------------------------------------


   def test_bulk_pending

      puts "================================================"
      puts "ORC_UnitTests::#{__method__.to_s}"
      puts
   
      system("orcManageDB -d")
      system("orcManageDB -c")
   
      @@arrInputFiles.each{|file|
         cmd = "orcQueueInput -P -s NRT -f #{file}"
         puts cmd
         assert(system(cmd), cmd)
      }
   
      cmd = "orcQueueInput -P -l"
      puts cmd
      assert(system(cmd), cmd)
      
      cmd = "orcQueueInput --Bulk"
      puts cmd
      assert(system(cmd), cmd)
      
      cmd = "orcQueueInput -P -l"
      puts cmd
      assert(system(cmd), cmd)
   
      cmd = "orcQueueInput -Q -l"
      puts cmd
      assert(system(cmd), cmd)

      @@logger.info("orcUnitTests::#{__method__.to_s} END")
      arr = Dir["/log/naosboa_orc*.log"]
      cmd = "cp #{arr[0]} /tmp/LOG_ORCUnitTest_#{__method__.to_s}"
      puts cmd
      system(cmd)

   
   end

   ## -------------------------------------------------------------

end


# =====================================================================


# -----------------------------------------------------------


